# trigger:
# - master

pool:
  vmImage: "ubuntu-latest"

container: mcr.microsoft.com/dotnet/core/sdk:2.2

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
  - script: |
      dotnet build ./source/ApiChassi/ApiChassi.sln
    displayName: "Build"

  - script: |
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./source/ApiChassi/ApiChassi.sln
    displayName: "Unit Test"

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: './.nuget/XopzApiTemplate.nuspec'
      configuration: 
      packDestination: 
      versioningScheme: 'off'
      basePath: '.'
