# trigger:
# - master

pool:
  vmImage: "vs2017-win2016"

# container: mcr.microsoft.com/dotnet/core/sdk:2.2

# variables:
#   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
  - script: |
      dotnet build ./source/ApiChassi/ApiChassi.sln
    displayName: "Build"

  - script: |
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./source/ApiChassi/ApiChassi.sln
    displayName: "Unit Test"

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: './.nuget/XopzApiTemplate.nuspec'
      versioningScheme: 'off'
      basePath: '.'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'XopzTeamNugetServiceConnection'