# trigger:
# - master

pool:
  vmImage: "ubuntu-latest"

container: mcr.microsoft.com/dotnet/core/sdk:2.2

steps:
  - script: |
      ls -la
      dotnet restore
      dotnet build
    displayName: "Build"

  - script: |
      dotnet test
    displayName: "Unit Test"
